### PR TITLE
Prepare repository for VersionBot integration

### PR DESCRIPTION
**Pull request by LucianBuzzo**

### CODE REVIEW

**Comment by lurch** [comment]
Okay, so how much is @hedss paying you? :wink:

**Comment by LucianBuzzo** [comment]
@lurch 💰 💰 💰

**Review by thgreasi — APPROVED** [review]
LGTM.
Is there a plan to make the docs versions follow Etcher's versioning?

**Comment by lurch** [comment]
@thgreasi I believe longer-term the plan is to integrate `etcher-homepage` directly into the `etcher` repo.

**Review by craigmulligan — APPROVED** [review]

**Pull request merged**
