### PR TITLE
fix: Replace Gitter link with forums link

### LINKED ISSUE #124: Replace link to Gitter with link to Forums
In wake of https://github.com/resin-io/etcher/pull/2134 the link to the Gitter chat should also be switched to linking to the Forum's Etcher topic

### PR DESCRIPTION
**Pull request by lurch**
Fixes #124

Change-type: patch

### CODE REVIEW

**Comment by jhermsmeier** [comment]
The header links pick on line 40 will also need updating:
https://github.com/resin-io/etcher-homepage/blob/c6e9c77a98665ed5da31f7638685f158b6525d49/config/index.js#L39-L42

**Comment by lurch** [comment]
Like this? :)

**Review by jhermsmeier — APPROVED** [review]
Yup, like that :)

**Comment by jhermsmeier** [comment]
Ref https://github.com/resin-io/etcher/pull/2134

**Pull request merged**
