### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by probonopd**
AppImage with uppercase A

### CODE REVIEW

**Comment by probonopd** [comment]
Ping @jviotti

**Comment by craigmulligan** [comment]
@probonopd, this needs to be fixed in `template.html` as well otherwise, the fix will be over-written in the next build. I can fix if you like?

**Comment by probonopd** [comment]
Yes, please go ahead, thanks!

**Comment by craigmulligan** [comment]
Fixed by https://github.com/resin-io/etcher-homepage/commit/461fc0e520cda5377d0bd194a7655c342e459607

**Pull request closed without merging**
